export enum ClientRoutes {
    Home = '/',
    Register = '/register',
    Login = '/login',
    ManageUsers = '/users',
    UserPage = '/user/:userId',
    UserPagePath = '/user/',
}

export enum Routes {
    Api = '/v1',
    Auth = '/auth',
    Admin = '/admin',
    ManageUsers = '/manageUsers',
    Login = '/login',
    Register = '/register',
    Logout = '/logout',
    Relog = '/relog',
    CountUserPages = '/countUserPages',
    GetUsers = '/users',
    GetUserPage = '/userPage',
    ToggleBlock = '/block',
    DeleteUsers = '/deleteUsers',
    ToggleAdmin = '/toggleAdmin',
    NewCollection = '/newCollection',
    UpdateCollection = '/updateCollection',
    DeleteCOllection = '/deleteCollection',
    NewItem = '/newItem',
    UpdateItem = '/updateItem',
    DeleteItem = '/deleteItem',
    ToggleLikeItem = '/likeItem',
    MakeAComment = '/newComment',
    DeleteComment = '/deleteComment',
}
