export enum ClientRoutes {
    Home = '/',
    Register = '/register',
    Login = '/login',
    ManageUsers = '/users',
    UserPage = '/user/:userId',
    UserPagePath = '/user/',
}

export enum Routes {
    Api = '/v1',
    Auth = '/auth',
    Admin = '/admin',
    ManageUsersSocket = '/manageUsers',
    ItemSocket = '/itemSocket',
    HomeSocket = '/homeSocket',
    Login = '/login',
    Register = '/register',
    Logout = '/logout',
    Relog = '/relog',
    CountUserPages = '/countUserPages',
    GetUsers = '/users',
    GetUserPage = '/userPage',
    ToggleBlock = '/block',
    DeleteUsers = '/deleteUsers',
    ToggleAdmin = '/toggleAdmin',
    NewCollection = '/newCollection',
    UpdateCollection = '/updateCollection',
    DeleteCollection = '/deleteCollection',
    NewItem = '/newItem',
    UpdateItem = '/updateItem',
    DeleteItem = '/deleteItem',
    ToggleLikeItem = '/likeItem',
    NewComment = '/newComment',
    EditComment = '/editComment',
    DeleteComment = '/deleteComment',
    GetUserCollections = '/userCollections',
    GetCollection = '/getCollection',
    GetCollectionItems = '/collectionItems',
    GetItem = '/getItem',
    GetItemComments = '/itemComments',
    SearchItems = '/searchItems',
}
