export enum ClientRoutes {
    Home = '/',
    Register = '/register',
    Login = '/login',
    ManageUsers = '/users',
    UserPagePath = '/user/',
    UserPage = ClientRoutes.UserPagePath + ':userId',
    NewCollection = 'newCollection',
    CollectionPath = '/collection/',
    CollectionPage = ClientRoutes.CollectionPath + ':collectionId',
    NewItem = 'newItem',
    ItemPath = '/item/',
    ItemPage = ClientRoutes.ItemPath + ':itemId',
}

export enum Routes {
    Api = '/v1',
    Auth = '/auth',
    Admin = '/admin',
    ManageUsersSocket = '/manageUsers',
    ItemSocket = '/itemSocket',
    HomeSocket = '/homeSocket',
    Login = '/login',
    Register = '/register',
    RefreshToken = '/refreshToken',
    Logout = '/logout',
    SetOnline = '/setOnline',
    CountUserPages = '/countUserPages',
    GetUsers = '/users',
    GetUserPage = '/userPage',
    ToggleBlock = '/block',
    DeleteUsers = '/deleteUsers',
    ToggleAdmin = '/toggleAdmin',
    NewCollection = '/newCollection',
    UpdateCollection = '/updateCollection',
    DeleteCollection = '/deleteCollection',
    NewItem = '/newItem',
    UpdateItem = '/updateItem',
    DeleteItem = '/deleteItem',
    ToggleLikeItem = '/likeItem',
    NewComment = '/newComment',
    EditComment = '/editComment',
    DeleteComment = '/deleteComment',
    GetUserCollections = '/userCollections',
    FindUserCollections = '/findUserCollections',
    GetCollection = '/getCollection',
    GetCollectionItems = '/collectionItems',
    FindCollectionItems = '/findCollectionItems',
    GetItem = '/getItem',
    GetItemComments = '/itemComments',
    SearchItems = '/searchItems',
}
