export enum Routes {
    Api = '/v1',
    Auth = '/auth',
    Admin = '/admin',
    ManageUsers = '/manageUsers',
    Login = '/login',
    Register = '/register',
    Logout = '/logout',
    Relog = '/relog',
    CountUserPages = '/countUserPages',
    GetUsers = '/users',
    GetUserPage = '/userPage',
    ToggleBlock = '/block',
    DeleteUsers = '/deleteUsers',
    ToggleAdmin = '/toggleAdmin',
    NewCollection = '/newCollection',
}
